[theme]
primaryColor = "#2b4c8c"              # Azul principal (sustituye el verde)
backgroundColor = "#FFFFFF"          # Fondo blanco
secondaryBackgroundColor = "#E8F0FA" # Azul claro para áreas secundarias
textColor = "#000000"                # Texto negro
font = "sans serif"                  # Fuente predeterminada
